apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-beta
spec:
  destination:
    # name: ''
    namespace: argo-new
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-cd
    repoURL: 'https://github.com/divshacker1010/argo-v2.9.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=orphan
    automated: null
