apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-beta
  finalizers: null

spec:
  project: default
  source:
    repoURL: https://github.com/divshacker1010/argo-v2.9.git
    path: templates
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-beta
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
