apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark-4
  finalizers: null

spec:
  project: default
  source:
    repoURL: https://github.com/divshacker1010/kubeshark-argo-test.git
    path: helm-chart
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ks
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
