apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-node-app
  #namespace: argocd-old
spec:
  project: default
  source:
    repoURL: https://github.com/divshacker1010/SampleNodeApp.git
    path: ./sample-node-application/manifest.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
